### ISSUE TITLE
使用nlog时部署日志功能不生效

### ISSUE THREAD

**Issue by zhaokuohaha** [linezero/Blog#2]
按照在您的[这篇博客](http://www.cnblogs.com/linezero/p/Logging.html)中我在我的项目中添加了Nlog,
开发的时候运行正常, 可是部署到服务器(CentOS7 64)位的时候却发现不能工作了,具体表现如下:
1. nlog.config 已经publish成功
2. 但是没有生成任何log文件夹和文件
3. 程序可以正常运行
4. 在centos那里重新修改log文件的文件路径, 还是不起作用.

**Comment by linezero** [comment]
https://github.com/linezero/NETCoreBBS/blob/dev/src/NetCoreBBS/Startup.cs#L76
需要在代码中也配置 nlog.config 文件。

**Comment by zhaokuohaha** [comment]
啊啊啊搞定了，谢谢。 这两天一直没记得写
